site_name: FreeBirds Club Documentation
site_url: https://docs.freebirdsclub.org

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tabs.link
  palette:
    - scheme: default
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized:
      type: datetime

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra_css:
  - css/custom.css

extra_javascript:
  - js/live-data.js

nav:
  - Home: index.md
  - Branding:
      - Overview: branding.md
      - Brand Guidelines: branding/01-brand-guidelines.md
      - Colors: branding/01-colors.md
  - Getting Started: 
      - Quick Start: getting-started/quick-start.md
  - Roadmap: roadmap.md
  - Market Analysis: market.md
  - Technical Docs: 
      - Overview: tech/index.md
      - API Reference: tech/api.md
  - Community: community.md
  - Languages:
      - English: index.md
      - Русский: index.ru.md
      - 中文: index.zh.md
      - Español: index.es.md
      - 日本語: index.ja.md
